export const ABOUT_TITLE = "Hi, \nI’m Oscar,\nsoftware developer";
export const TECHNOLOGIES = [
  "Javascript",
  "Typescript",
  "Php",
  "Golang",
  "Dart",
  "SQL",
  "NoSQL",
  "Redis",
  "React",
  "Express",
  "Flutter",
  "Laravel",
  "MongoDB",
  "AngularJS",
  "VueJS",
  "Angular",
  "PostgreSQL",
  "MySQL",
  "Firebase",
  "Sass",
  "Styled components",
  "Less",
  "Webpack",
  "Babel",
];
