import { IconType } from "react-icons/lib"
import { FaLess } from "react-icons/fa"
import { RiVuejsFill, RiQuestionLine } from "react-icons/ri"
import { AiOutlineAntDesign } from "react-icons/ai"
import { GrMysql } from "react-icons/gr"
// TODO: improve imports
import {
  SiAngular,
  SiCss3,
  SiBabel,
  SiBootstrap,
  SiDart,
  SiDocker,
  SiElectron,
  SiFlutter,
  SiGatsby,
  SiGraphql,
  SiGrunt,
  SiGulp,
  SiHtml5,
  SiIonic,
  SiJest,
  SiJavascript,
  SiPostcss,
  SiLaravel,
  SiMaterialUi,
  SiMongodb,
  SiNextDotJs,
  SiNodeDotJs,
  SiNpm,
  SiPostgresql,
  SiPhp,
  SiRedux,
  SiReact,
  SiSass,
  SiSencha,
  SiSvelte,
  SiTailwindcss,
  SiTypescript,
  SiWebpack,
  SiYarn,
  SiStyledComponents,
  SiComposer,
  SiPrettier,
  SiSubversion,
  SiFirebase,
  SiAmazonaws,
  SiJquery,
  SiGit,
  SiPython,
  SiAngularjs,
  SiRedis,
  SiFlask,
} from "react-icons/si"

const ICONS: {
  [key: string]: IconType
} = {
  SiAngular,
  SiCss3,
  SiBabel,
  SiBootstrap,
  SiDart,
  SiDocker,
  SiElectron,
  SiFlutter,
  SiGatsby,
  GrMysql,
  SiGraphql,
  SiGrunt,
  SiGulp,
  SiHtml5,
  SiIonic,
  SiJest,
  SiJavascript,
  SiPostcss,
  SiLaravel,
  SiMaterialUi,
  SiMongodb,
  SiNextDotJs,
  SiNodeDotJs,
  SiNpm,
  SiPostgresql,
  SiPhp,
  SiRedux,
  SiReact,
  SiSass,
  SiSencha,
  SiSvelte,
  SiTailwindcss,
  SiTypescript,
  SiWebpack,
  SiYarn,
  SiStyledComponents,
  SiComposer,
  SiPrettier,
  SiSubversion,
  SiFirebase,
  SiAmazonaws,
  SiJquery,
  SiGit,
  SiPython,
  SiAngularjs,
  SiRedis,
  SiFlask,
  RiVuejsFill,
  RiQuestionLine,
  AiOutlineAntDesign,
  FaLess,
}

export const getIcon = (iconString: string): IconType => ICONS[`${iconString}`]
