import { useContext } from "react"
import Head from "next/head"

import NotFoundPage from "../src/components/NotFound/NotFound.component"

import { ThemeProvider } from "styled-components"
import { lightTheme, darkTheme } from "../src/styles/themes"
import { GlobalStyles } from "../src/styles/global"
import { AppContext } from "../src/context/appContext"

export default function NotFound() {
  const { isLightTheme } = useContext(AppContext)

  return (
    <ThemeProvider theme={isLightTheme ? lightTheme : darkTheme}>
      <GlobalStyles />
      <Head>
        <title>404 | Not found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotFoundPage />
    </ThemeProvider>
  )
}
