import "@fontsource/istok-web/400.css"
import "@fontsource/istok-web/700.css"
import "tippy.js/dist/tippy.css"

import { useState } from "react"
import Head from "next/head"

import HomePage from "../src/components/Home/Home.component"
import Layout from "../src/components/shared/layout/Layout.component"
import FullScreenSlider from "../src/components/shared/FullScreenSlider/FullScreenSlider.component"

import AppProvider from "../src/context/appContext"
import FullScreenSliderProvider from "../src/context/fullScreenSliderContext"

import { ThemeProvider } from "styled-components"
import { lightTheme, darkTheme } from "../src/styles/themes"
import { GlobalStyles } from "../src/styles/global"
import { AnimatePresence } from "framer-motion"

export default function Home() {
  const [isLightTheme, setIsLightTheme] = useState<boolean>(false)
  const switchTheme = (newValue: boolean) => setIsLightTheme(newValue)

  return (
    <AppProvider>
      <FullScreenSliderProvider>
        <ThemeProvider theme={isLightTheme ? lightTheme : darkTheme}>
          <GlobalStyles />
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Layout switchTheme={switchTheme}>
            <HomePage />
          </Layout>
          <AnimatePresence key="fullscreen-wrapper">
            <FullScreenSlider />
          </AnimatePresence>
        </ThemeProvider>
      </FullScreenSliderProvider>
    </AppProvider>
  )
}
