import Head from 'next/head'
// import Image from 'next/image'
import HomePage from '../src/components/Home/Home.component'
import Layout from '../src/components/shared/layout/Layout.component'


export default function Home() {
  const switchTheme = (newValue:any) => {
    console.log(newValue)
  }
  return ( 
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout switchTheme={switchTheme}>
          <HomePage />
        </Layout>
      </div> 
  )
}
