import "@fontsource/istok-web/400.css";
import "@fontsource/istok-web/700.css";

import { useState } from "react";
import Head from "next/head";
// import Image from 'next/image'
import HomePage from "../src/components/Home/Home.component";
import Layout from "../src/components/shared/layout/Layout.component";
import AppProvider from "../src/context/appContext";

import { ThemeProvider } from "styled-components";
import { lightTheme, darkTheme } from "../src/styles/themes";
import { GlobalStyles } from "../src/styles/global";

export default function Home() {
  const [isLightTheme, setIsLightTheme] = useState(false);
  const switchTheme = (newValue: boolean) => setIsLightTheme(newValue);

  return (
    <AppProvider>
      <ThemeProvider theme={isLightTheme ? lightTheme : darkTheme}>
        <GlobalStyles />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout switchTheme={switchTheme}>
          <HomePage />
        </Layout>
      </ThemeProvider>
    </AppProvider>
  );
}
